version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - PGUSER=${PGUSER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    ports:
      - ${MONGO_PORT}:27017

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
volumes:
  mongo_db:
  pg_db:
  mysql_db:
